### ISSUE TITLE
ImportError: cannot import name 'secure_filename' from 'werkzeug'

### ISSUE THREAD

**Issue by hakube** [coleifer/scout#10]
Can you help me fix this, I'm getting this error

`Traceback (most recent call last):
  File "/home/jacob/.local/bin/scout", line 11, in <module>
    load_entry_point('scout==3.0.2', 'console_scripts', 'scout')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jacob/.local/lib/python3.6/site-packages/scout/server.py", line 10, in <module>
    from scout.models import database
  File "/home/jacob/.local/lib/python3.6/site-packages/scout/models.py", line 14, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename'
`

**Comment by coleifer** [comment]
You need to upgrade your scout.

**Comment by coleifer** [comment]
Actually that's my bad - I needed to tag a new release. 3.0.3
