### ISSUE TITLE
error

### ISSUE THREAD

**Issue by passionate2023** [coleifer/scout#11]
on running python scout/ /path/to/search-index.db

conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

**Comment by coleifer** [comment]
Make sure the directories exist and you have permission to write to them.

**Comment by passionate2023** [comment]
permission exist, still gets the error

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\Scripts\scout-script.py", line 33, in <module>
    sys.exit(load_entry_point('scout==3.0.3', 'console_scripts', 'scout')())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\scout-3.0.3-py3.10.egg\scout\server.py", line 212, in main
    app = parse_options()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\scout-3.0.3-py3.10.egg\scout\server.py", line 208, in parse_options
    return create_server(config, config_file)

**Comment by coleifer** [comment]
You'll need to debug. Presumably some error on your side with the filename. You can drop a print statement before the sqlite3 connect call and see what file it's trying to use.
