### ISSUE TITLE
docker image: no module named 'gevent.wsgi'

### ISSUE THREAD

**Issue by fabrixxm** [coleifer/scout#6]
```
$ docker run -it --rm -p 9004:9004 coleifer/scout
Traceback (most recent call last):
  File "/srv/server.py", line 14, in <module>
    from gevent.wsgi import WSGIServer
ModuleNotFoundError: No module named 'gevent.wsgi'
```

**Comment by coleifer** [comment]
No clue, it clearly installs gevent.

**Comment by ravishaheshan** [comment]
I can confirm this. Issue still exists
![Screenshot 2019-11-27 at 4 38 26 PM](https://user-images.githubusercontent.com/47412190/69718444-63e2c900-1134-11ea-9a50-4700f68a5221.png)

**Comment by coleifer** [comment]
Can you share the command you ran, @ravishaheshan ?

**Comment by fabrixxm** [comment]
```
$ docker run -it --rm -p 9004:9004 coleifer/scout
Unable to find image 'coleifer/scout:latest' locally
latest: Pulling from coleifer/scout
5d20c808ce19: Pull complete
7fe10f100437: Pull complete
22f847861baf: Pull complete
e93e748c3c8b: Pull complete
Digest: sha256:9336bd3cc28b7c98687ceb76ea229a4ab2a97aac4e15999449ada7db850e2835
Status: Downloaded newer image for coleifer/scout:latest
Traceback (most recent call last):
  File "/srv/server.py", line 14, in <module>
    from gevent.wsgi import WSGIServer
ModuleNotFoundError: No module named 'gevent.wsgi'
```

The code try to import `WSGIServer` from `gevent.wsgi` module , but [gevent's docs](http://www.gevent.org/api/gevent.pywsgi.html) say that `WSGIServer` is in `gevent.pywsgi` module

and indeed:

```
$ docker run --rm -it -p 9004:9004/tcp --entrypoint /bin/sh coleifer/scout 
/data # python3
Python 3.6.8 (default, Apr 22 2019, 10:24:07) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
>>> from gevent.wsgi import WSGIServer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gevent.wsgi'
>>> from gevent.pywsgi import WSGIServer
>>> 
```

**Comment by coleifer** [comment]
Ahh! Thanks, I appreciate you pointing that out. I've pushed a new image and committed changes as well so it should be working.
